name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install dependencies
      run: |
        cd web
        npm ci

    - name: Generate Prisma client
      run: |
        cd web
        npx prisma generate

    - name: Run linter
      run: |
        cd web
        npm run lint

    - name: Run tests
      run: |
        cd web
        npm run test

    - name: Build project
      run: |
        cd web
        npm run build
